name: Setup repository
on:
    workflow_dispatch:
jobs:
    setup-repository:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1
            - name: Create variables
              continue-on-error: true
              env:
                  GH_TOKEN: ${{ secrets.CICD_TOKEN }}
              run: ./scripts/set_variables.sh ./scripts/.deploy_vars.env
            - name: Create secrets
              continue-on-error: true
              env:
                  GH_TOKEN: ${{ secrets.CICD_TOKEN }}
              run: ./scripts/set_secrets.sh ./scripts/.deploy_secrets.env
